# Custom Resource Definition - Scale on Azure Queue
# curl http://localhost:8001/apis/apex-sample.com/v1/

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azurequeues.apex-sample.com
spec:
  group: apex-sample.com
  version: v1
  scope: Namespaced
  names:
    plural: azurequeues
    singular: azurequeue
    kind: AzureQueue
    shortNames:
    - aq